name:                TP-FINAL
version:             0.1.0.0
github:              "githubuser/TP-FINAL"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TP-FINAL#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- pretty
- strict
- time
- time-parsers
- array
- haskeline >= 0.8.0.0
- mtl
- exceptions
- QuickCheck


default-extensions:
- GADTs
- StandaloneDeriving

ghc-options:
- -Wunused-imports
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  TP-FINAL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP-FINAL

tests:
  TP-FINAL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP-FINAL
